# Setup
title:               '@mrlee323'
tagline:             '기술 블로그'
description:         '성장하는 개발자'
url:                 https://mrlee323.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mirim Lee
  url:               
  email:             mrlee3233@gmail.com

# Gems
plugins:
  - jekyll-paginate

